# Copyright 2026 OpenHW Foundation
# SPDX-License-Identifier: Apache-2.0
# Original riscv-tests instruction bodies with the bounded Cook M-mode environment.
# Not equivalent to the original p-mode privilege/PMP coverage.
common: &common
  iterations: 1
  path_var: TESTS_PATH
  gcc_opts: "-static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -mno-relax -I.github/cook/env/m/ -I<path_var>/riscv-tests/isa/macros/scalar/"
testlist:
  - test: rv32ui-m-stage1-sub
    <<: *common
    asm_tests: <path_var>/riscv-tests/isa/rv32ui/sub.S
  - test: rv32ui-m-stage1-xor
    <<: *common
    asm_tests: <path_var>/riscv-tests/isa/rv32ui/xor.S
  - test: rv32ui-m-stage1-sll
    <<: *common
    asm_tests: <path_var>/riscv-tests/isa/rv32ui/sll.S
